name: Verify Changes

on:
  pull_request:
    branches: [main]

jobs:
  lint-code:
    uses: ./.github/workflows/lint-code.yaml
    permissions:
      contents: read
      packages: read
    secrets: inherit

  test-open-tofu:
    uses: ./.github/workflows/test-open-tofu.yaml
    permissions:
      contents: read
    secrets: inherit
