name: Lint Code

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: false
        default: '.'

jobs:
  lint-code:
    name: Lint Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run repo lint command
        working-directory: ${{ inputs.working-directory }}
        run: pnpm ci:lint
        