name: KAD Semantic Release Dry Run

on:
  workflow_call:

jobs:
  semantic-release-dry-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install

      - name: Semantic Release (Dry Run)
        id: release-notes-preview
        uses: guilhermetod/semantic-release-notes-preview@v1.0.0

      - name: Comment release notes preview
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Thank you for you contribution. Below is a preview of the release notes if your PR gets merged.

            ---

            ${{ steps.release-notes-preview.outputs.releaseNotes }}. 