name: Test OpenTofu

on:
  workflow_call:

jobs:
  test-open-tofu:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - run: tofu init
        working-directory: open-tofu/modules/environment

      - run: tofu test
        working-directory: open-tofu/modules/environment
