name: Test OpenTofu

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Path to the OpenTofu module to test'
        required: true
        type: string

jobs:
  test-open-tofu:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_version: latest

      - name: Init and test
        working-directory: ${{ inputs.working-directory }}
        run: |
          tofu init
          tofu test
