name: Test OpenTofu

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Path to the OpenTofu module to test'
        required: true
        type: string

jobs:
  test-open-tofu:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - working-directory: ${{ inputs.working_directory }}
        run: |
          tofu init
          tofu test
