name: Upgrade Dependencies

on:
  workflow_call:      

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: renovatebot/github-action@v46.3.5
        with:
          token: ${{ secrets.KAD_WORKFLOW_AUTOMATION }}
        env:
          RENOVATE_CI: true
          RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate[bot]@users.noreply.github.com>"
          RENOVATE_HOST_RULES: '[{"matchHost":"npm.pkg.github.com","hostType":"npm","token":"${{ secrets.KAD_WORKFLOW_AUTOMATION }}"}]'
          RENOVATE_ONBOARDING: "false"
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: debug
          CI: "true"

